"""empty message

Revision ID: 1e3dbedc8a8d
Revises: 81598f37e31b
Create Date: 2019-02-26 01:59:08.641698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e3dbedc8a8d'
down_revision = '81598f37e31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('permit_number', sa.String(length=250), nullable=False),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.Column('firs_name', sa.String(length=250), nullable=False),
    sa.Column('speciality', sa.String(length=250), nullable=False),
    sa.Column('city', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('permit_number')
    )
    op.create_table('nurse',
    sa.Column('access_id', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('access_id')
    )
    op.create_table('appointment',
    sa.Column('patient_card_number', sa.String(length=250), nullable=False),
    sa.Column('doctor_permit_number', sa.String(length=250), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.Column('appointment_type', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['doctor_permit_number'], ['doctor.permit_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_card_number'], ['patient.card_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_card_number')
    )
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_permit_number', sa.String(length=250), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_permit_number'], ['doctor.permit_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('patient', 'address',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('patient', 'birth_day',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('patient', 'email',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('patient', 'gender',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('patient', 'phone_number',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'phone_number',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('patient', 'gender',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('patient', 'email',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('patient', 'birth_day',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('patient', 'address',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.drop_table('availability')
    op.drop_table('appointment')
    op.drop_table('nurse')
    op.drop_table('doctor')
    # ### end Alembic commands ###
