"""empty message

Revision ID: b6c4e6bfa508
Revises: fc4a26fd1a6b
Create Date: 2019-02-27 01:44:34.097184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c4e6bfa508'
down_revision = 'fc4a26fd1a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'appointment', 'doctor', ['doctor_permit_number'], ['permit_number'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointment', 'patient', ['patient_card_number'], ['card_number'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    # ### end Alembic commands ###
