"""empty message

Revision ID: c17c7bb33627
Revises: b6c4e6bfa508
Create Date: 2019-02-28 18:51:13.564558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c17c7bb33627'
down_revision = 'b6c4e6bfa508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('location', sa.String(length=250), nullable=False))
    op.add_column('doctor', sa.Column('password', sa.String(length=250), nullable=False))
    op.drop_column('doctor', 'city')
    op.add_column('nurse', sa.Column('email', sa.String(length=250), nullable=False))
    op.add_column('nurse', sa.Column('first_name', sa.String(length=250), nullable=False))
    op.add_column('nurse', sa.Column('last_name', sa.String(length=250), nullable=False))
    op.add_column('patient', sa.Column('first_name', sa.String(length=250), nullable=False))
    op.add_column('patient', sa.Column('last_name', sa.String(length=250), nullable=False))
    op.add_column('patient', sa.Column('password', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'password')
    op.drop_column('patient', 'last_name')
    op.drop_column('patient', 'first_name')
    op.drop_column('nurse', 'last_name')
    op.drop_column('nurse', 'first_name')
    op.drop_column('nurse', 'email')
    op.add_column('doctor', sa.Column('city', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('doctor', 'password')
    op.drop_column('doctor', 'location')
    # ### end Alembic commands ###
