"""empty message

Revision ID: d12c8432a974
Revises: 
Create Date: 2019-04-03 17:11:26.707742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12c8432a974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'doctor', 'clinics', ['clinic_id'], ['clinic_id'])
    op.add_column('nurse', sa.Column('clinic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nurse', 'clinics', ['clinic_id'], ['clinic_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nurse', type_='foreignkey')
    op.drop_column('nurse', 'clinic_id')
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    # ### end Alembic commands ###
