"""empty message

Revision ID: e5398a670d62
Revises: 4be837c0f43b
Create Date: 2019-04-03 16:51:03.116260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5398a670d62'
down_revision = '4be837c0f43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('clinic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('no_doctors', sa.INTEGER(), nullable=False),
    sa.Column('no_nurses', sa.INTEGER(), nullable=False),
    sa.Column('no_rooms', sa.INTEGER(), nullable=False),
    sa.Column('schedule', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('clinic_id')
    )
    op.add_column('doctor', sa.Column('clinic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'doctor', 'clinics', ['clinic_id'], ['clinic_id'])
    op.add_column('nurse', sa.Column('clinic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nurse', 'clinics', ['clinic_id'], ['clinic_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nurse', type_='foreignkey')
    op.drop_column('nurse', 'clinic_id')
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    op.drop_column('doctor', 'clinic_id')
    op.drop_table('clinics')
    # ### end Alembic commands ###
